import Image from 'next/image'
import { Inter } from 'next/font/google'
import Hero from '../components/Hero'
import Head from 'next/head'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div>
    <Head>
      <title> Photography website </title>
      <meta name="Portfolio website" content='Generated by Sundown'/>
      <link rel="icon" href='/favicon.ico'/> 
    </Head>
    <Hero heading="Cosmo Arts" message="Out of the world photography"/>
    </div>
     )
}
